--CRIAR BANCO DE DADOS
CREATE DATABASE Senatur_Tarde;

--USANDO O BANCO DE DADOS
USE Senatur_Tarde;

--CRIAR TABELAS DO BANCO 

CREATE TABLE Pacotes(
	IdPacote INT PRIMARY KEY IDENTITY,
	NomePacote VARCHAR(255) NOT NULL,
	Descricao TEXT NOT NULL,
	DataIda DATE NOT NULL,
	DataVolta DATE NOT NULL,
	Valor DECIMAL(18,2)NOT NULL,
	Ativo bit DEFAULT(1),
	NomeCidade VARCHAR(255) NOT NULL
);

CREATE TABLE TiposUsuario (
	IdTiposUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL
);

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR(255) NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	IdTiposUsuario INT FOREIGN KEY REFERENCES TiposUsuario(IdTiposUsuario)
);


